# Generated by Django 5.2 on 2026-03-29
# Add scheduled_at field to QueuedMail for email scheduling feature

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_question_type_add_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmail',
            name='scheduled_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='If set, the email will be sent at this time instead of immediately.',
                null=True,
                verbose_name='Scheduled for',
            ),
        ),
    ]
