# Generated by Django 6.0.7 on 2026-08-20 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_locale_choices_native_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If disabled, the feedback is anonymous to the speaker and not shown publicly.', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.feedback', verbose_name='Parent feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending Review'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='published', max_length=20, verbose_name='Status'),
        ),
    ]
