# Generated by Django 6.0.7 on 2026-08-20 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_feedback_author_feedback_is_public_feedback_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banned_users',
            field=models.ManyToManyField(blank=True, help_text='Users who are banned from submitting feedback or interacting with this event.', related_name='banned_events', to=settings.AUTH_USER_MODEL, verbose_name='Banned users'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Indicates whether this feedback has been reported by a user.', verbose_name='Is reported'),
        ),
    ]
