# Generated by Django 6.0.7 on 2026-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_event_banned_users_feedback_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='report_count',
            field=models.IntegerField(default=0, help_text='Number of times this feedback has been reported.', verbose_name='Report count'),
        ),
    ]
