# Generated by Django 6.0.7 on 2026-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_loungemeshaccesstoken_loungemeshserver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('N', 'Number'), ('S', 'Text (one line)'), ('T', 'Multiline text'), ('B', 'Confirm Checkbox'), ('C', 'Radio button (Choose one option)'), ('L', 'Dropdown (Choose one option)'), ('M', 'Checkbox (Choose one or several options)'), ('F', 'File upload'), ('D', 'Date'), ('H', 'Time'), ('W', 'Date and time'), ('CC', 'Country code (ISO 3166-1 alpha-2)'), ('TEL', 'Phone number'), ('DES', 'Text field'), ('URL', 'URL')], max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='variant',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text (one-line)'), ('text', 'Multi-line text'), ('url', 'URL'), ('video', 'Video link'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Confirmation'), ('file', 'File upload'), ('choices', 'Radio button (Choose one option)'), ('multiple_choice', 'Checkbox (Choose one or several options)'), ('select', 'Select (one option)'), ('country', 'Country List'), ('tel', 'Phone number')], default='string', max_length=15),
        ),
    ]
