# Generated by Django 6.0.7 on 2026-09-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_voucher_limit_products'),
    ]

    operations = [
    ]
